# Generated by Django 5.2.18 on 2026-10-06 17:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Fornecedor',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=180)),
                ('documento', models.CharField(blank=True, max_length=20)),
            ],
            options={
                'verbose_name': 'fornecedor',
                'verbose_name_plural': 'fornecedores',
                'ordering': ['nome'],
            },
        ),
        migrations.CreateModel(
            name='ProcessoLicitatorio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.CharField(max_length=30, unique=True)),
                ('modalidade', models.CharField(max_length=80)),
                ('numero_licitacao', models.CharField(max_length=30)),
                ('saldo_atualizado_em', models.DateField(help_text='Data do relatório de saldo usado como referência.')),
            ],
            options={
                'verbose_name': 'processo licitatório',
                'verbose_name_plural': 'processos licitatórios',
                'ordering': ['-saldo_atualizado_em', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='ItemLicitado',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('numero', models.PositiveIntegerField()),
                ('descricao', models.CharField(max_length=500)),
                ('unidade', models.CharField(max_length=30)),
                ('valor_unitario', models.DecimalField(decimal_places=4, max_digits=12)),
                ('saldo_informado', models.DecimalField(decimal_places=4, max_digits=12)),
                ('fornecedor', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='compras.fornecedor')),
                ('processo', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='itens', to='compras.processolicitatorio')),
            ],
            options={
                'verbose_name': 'item licitado',
                'verbose_name_plural': 'itens licitados',
                'ordering': ['processo__numero', 'numero'],
            },
        ),
        migrations.CreateModel(
            name='Pedido',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('solicitante', models.CharField(max_length=120)),
                ('pessoa_retirada', models.CharField(max_length=120)),
                ('destino', models.CharField(max_length=180)),
                ('finalidade', models.TextField()),
                ('quantidade', models.DecimalField(decimal_places=4, max_digits=12)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('atualizado_em', models.DateTimeField(auto_now=True)),
                ('item', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='pedidos', to='compras.itemlicitado')),
            ],
            options={
                'verbose_name': 'pedido',
                'verbose_name_plural': 'pedidos',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.AddConstraint(
            model_name='itemlicitado',
            constraint=models.UniqueConstraint(fields=('processo', 'numero'), name='item_unico_por_processo'),
        ),
    ]
